name: Build
on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          registry: ghcr.io
          image: urn1350.net
          username: Emersont1
          password: ${{ secrets.CONTAINER_REGISTRY }}
          tags: latest
